### ISSUE TITLE
只能查询到uid为1开头的信息

### ISSUE THREAD

**Issue by Neptinium** [CRAZYShimakaze/zhenxun_extensive_plugin#1]
![IMG_20220609_162853.jpg](https://user-images.githubusercontent.com/65025626/172801782-f0dd3d9f-c006-46c9-939e-0da6cfbe9fc6.jpg)
并不是因为橱窗没开放，试过好几个了。uid开头2以上的都查不了。不知道是我配置问题还是插件问题。

**Comment by CRAZYShimakaze** [comment]
是B服账号吗？B服查不了的，我自己测试了一个2开头的官服id，是可以查询的诶。
![image](https://user-images.githubusercontent.com/49238273/172986082-9089c7cc-7409-47a2-9752-c588eba9c0ad.jpeg)

**Comment by Neptinium** [comment]
> 是B服账号吗？B服查不了的，我自己测试了一个2开头的官服id，是可以查询的诶。
> ![image](https://user-images.githubusercontent.com/49238273/172986082-9089c7cc-7409-47a2-9752-c588eba9c0ad.jpeg)

216开头那个是官服的，当时确实会出现所说情况。不过今天再试就正常了。总之谢谢解答。
