### ISSUE TITLE
这个是网络原因吗？

### ISSUE THREAD

**Issue by qq985382384** [CRAZYShimakaze/zhenxun_extensive_plugin#10]
![501510933-3949420661-2E96040B05A14031AA962FE54B1C81ED](https://user-images.githubusercontent.com/53076564/178282002-049f11f2-ccf3-4e21-a192-8d52b004edf0.png)
![501510933-1972155868-DBAF63D4A31F84E61DE9A0D82BFAA75E](https://user-images.githubusercontent.com/53076564/178282226-ca2f7696-72a2-459f-9bb4-bac714262bc2.png)

**Comment by CRAZYShimakaze** [comment]
是最新版本的代码吗？最新版应该要么超时报错，要么出来完整的数据的。

**Comment by CRAZYShimakaze** [comment]
> 橱窗第一位角色好没问题 ![501510933-1626433658-4E9976A7DAB82DA4417759A3063BA85B](https://user-images.githubusercontent.com/53076564/178283019-a6e1f1c8-143c-4fa0-bf51-0c9aa8485759.png)

更新一下最新版本代码吧，应该解决了
