### ISSUE TITLE
genshin_recommend 似乎无法正常更新下载alias.json

### ISSUE THREAD

**Issue by SuLiuming** [CRAZYShimakaze/zhenxun_extensive_plugin#100]
![image](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/88638705/51958ec0-28d7-4e51-8be7-578d626727a0)

**Comment by CRAZYShimakaze** [comment]
config里的github的镜像站换一下，换成https://mirror.ghproxy.com/https://raw.githubusercontent.com

**Comment by SuLiuming** [comment]
多谢 已解决
