### ISSUE TITLE
更新黄泉面板报错

### ISSUE THREAD

**Issue by qwe252500804** [CRAZYShimakaze/zhenxun_extensive_plugin#101]
## 概述
黄泉面板更新不出来

## 系统环境
windows

## 重现步骤
更新星铁面板

UID100384525
![@7~D(L90W6VRA 1AW@H A 4](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/126217450/5b65d03b-2e24-4732-bb46-459499bc52c8)

**Comment by CRAZYShimakaze** [comment]
修复啦，更新一下吧

**Comment by qwe252500804** [comment]
![{3FAA3F69-B74D-4a18-B293-F695054D0157}](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/126217450/0165fe2c-a6e5-4a5a-9dc9-df0387abaf44)
![{303A5773-DAE0-4356-85FE-BE323987457F}](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/126217450/36afb716-85bd-499e-86d5-08107e24ed07)

**Comment by qwe252500804** [comment]
下载这个下载出来是个1kb的文件，手动下载打不开

**Comment by CRAZYShimakaze** [comment]
这次应该可以啦

**Comment by qwe252500804** [comment]
解决了，谢谢
