### ISSUE TITLE
原神星铁插件更新后无法使用

### ISSUE THREAD

**Issue by qwe252500804** [CRAZYShimakaze/zhenxun_extensive_plugin#103]
## 概述
更新后插件无法加载

## 系统环境
windows11

## Bug行为
真寻如何反馈

## 附件
附上图片或日志，日志请用格式：
 
![00](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/126217450/6d203f17-3d79-43ba-8ffe-2f58728c661c)
![0](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/126217450/63412e93-736a-4a70-acbf-77bfceda4195)

> ```
> 日志内容
> ```

**Comment by CRAZYShimakaze** [comment]
这个文件夹在仓库里
