### ISSUE TITLE
圣遗物推荐报错

### ISSUE THREAD

**Issue by qwe252500804** [CRAZYShimakaze/zhenxun_extensive_plugin#105]
## 概述
圣遗物推荐报错

## 系统环境
windows

## 重现步骤
命令信息(如果是原神、星铁插件请提供uid、角色名等)：
uid：100421685
克洛琳德谐律套推荐
## 附件
附上图片或日志，日志请用格式：
 
![image](https://github.com/user-attachments/assets/0c67418f-3f92-4743-883d-799f8ca14488)

**Comment by CRAZYShimakaze** [comment]
已修复

**Comment by qwe252500804** [comment]
![image](https://github.com/user-attachments/assets/9b120119-c2d4-4033-bfa8-ab4f96bd0cb6)
发完指令没反应

**Comment by qwe252500804** [comment]
![image](https://github.com/user-attachments/assets/818e8d9b-4922-426c-b440-b2c66e8fb346)
而且圣遗物导入也没用

**Comment by CRAZYShimakaze** [comment]
看看genshin_role_info/res/json_data/artifact.json是否是最新的，info里有没有谐律套

**Comment by qwe252500804** [comment]
有的

**Comment by CRAZYShimakaze** [comment]
> ![image](https://private-user-images.githubusercontent.com/126217450/359581828-818e8d9b-4922-426c-b440-b2c66e8fb346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTczNDMsIm5iZiI6MTcyNDI1NzA0MywicGF0aCI6Ii8xMjYyMTc0NTAvMzU5NTgxODI4LTgxOGU4ZDliLTQ5MjItNDI2Yy1iNDQwLWIyYzY2ZThmYjM0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxNjE3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc4ZGFmMzIzYjNhOTg2MWU2OGQ3YTJkZGQ5ZGRmNzA2Nzk4NGRjNWY2ZDRlZTJiNmNiM2MxYmU5NzQ3MjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V23htAsQdjhdgX1Uzt_rjpxUNmtGqFoSEI1TWcXUeMA) 而且圣遗物导入也没用

暂不支持圣遗物导入

**Comment by CRAZYShimakaze** [comment]
> ![image](https://private-user-images.githubusercontent.com/126217450/359579981-9b120119-c2d4-4033-bfa8-ab4f96bd0cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTczNDMsIm5iZiI6MTcyNDI1NzA0MywicGF0aCI6Ii8xMjYyMTc0NTAvMzU5NTc5OTgxLTliMTIwMTE5LWMyZDQtNDAzMy1iZmE4LWFiNGY5NmJkMGNiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxNjE3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDkzM2Q3ZWI3M2ZiNWEyMWI4MDJiNGYwNDQzZTYzNmUzZDMxMDBlMGY2N2I1ZGQyNjI0NzU3ZGMzMDA3OTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iZkqBN5SPN_BWqmthFib_O4-IxRHruIaRxMgsSjkfN0) 发完指令没反应

我这里是可以的,确认下插件是否和仓库一致.

**Comment by qwe252500804** [comment]
圣遗物导入有什么办法解决么

**Comment by CRAZYShimakaze** [comment]
> 圣遗物导入有什么办法解决么

这个功能依赖于另一个导出项目，现在还不太稳定
