### ISSUE TITLE
求问题#3的详细步骤

### ISSUE THREAD

**Issue by whatxy** [CRAZYShimakaze/zhenxun_extensive_plugin#14]
跟问题#3的一样，不知道怎么改

**Comment by whatxy** [comment]
![image](https://user-images.githubusercontent.com/110091393/181233835-12b68ac7-acad-4751-95ab-7375a89a4867.png)

**Comment by whatxy** [comment]
这是安装的原石的东西
![image](https://user-images.githubusercontent.com/110091393/181234236-8f66b022-c36a-4fed-9edd-603f29721950.png)

**Comment by CRAZYShimakaze** [comment]
和github插件冲突了，可以把原神角色卡插件优先级调高一些:
`char_card = on_command("原神角色卡", priority=4, block=True)`
或者调低github插件的优先级。

**Comment by whatxy** [comment]
![image](https://user-images.githubusercontent.com/110091393/181268736-2837f0af-c31c-4e52-bc0f-90d7802d5be2.png)
dal大佬这卡后端是什么原因呀，一直停这不动还要自己按一下回车

**Comment by whatxy** [comment]
好像挂一会它自己就好了，非常感谢大佬的解惑

**Comment by CRAZYShimakaze** [comment]
> ![image](https://user-images.githubusercontent.com/110091393/181268736-2837f0af-c31c-4e52-bc0f-90d7802d5be2.png) dal大佬这卡后端是什么原因呀，一直停这不动还要自己按一下回车

这个是网络问题，网络连通性不好就会卡在这。
