### ISSUE TITLE
genshin_role_card  linux下放置在哪个plugin文件夹都无法使用

### ISSUE THREAD

**Issue by JiJiang233** [CRAZYShimakaze/zhenxun_extensive_plugin#19]
机器人不响应指令，后台无报错

**Comment by JiJiang233** [comment]
python版本3.8

**Comment by CRAZYShimakaze** [comment]
后台日志发一下

**Comment by JiJiang233** [comment]
08-20 18:39:50 [SUCCESS] nonebot | NoneBot is initializing...
08-20 18:39:50 [INFO] nonebot | Current Env: dev
08-20 18:39:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
08-20 18:39:52 [SUCCESS] nonebot | Succeeded to import "broadcast"
08-20 18:39:52 [SUCCESS] nonebot | Succeeded to import "hooks"
08-20 18:39:52 [SUCCESS] nonebot | Succeeded to import "admin_help"
08-20 18:39:52 [SUCCESS] nonebot | Succeeded to import "super_help"
08-20 18:39:52 [SUCCESS] nonebot | Succeeded to import "rule"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "custom_welcome_message"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "update_group_member_info"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "switch_rule"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "admin_config"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "timing_task"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "admin_bot_manage"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "use"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "shop_handle"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "shop_handle"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "use"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "reset_today_gold"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "gold"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "my_props"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "buy"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "shop"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "ban"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "scripts"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "plugin_shop"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "apscheduler"
08-20 18:39:53 [SUCCESS] nonebot | Succeeded to import "invite_manager"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "nickname"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "init_plugin_config"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "update_info"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "group_handle"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "update_friend_group_info"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "reload_setting"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "set_admin_permissions"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "exec_sql"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "clear_data"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "super_task_switch"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "bot_friend_group"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "manager_group"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "super_cmd"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "chat_message_handle"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "chat_message"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "chat_history"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "help"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "ai"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "epic"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "send_image"
08-20 18:39:54 [SUCCESS] nonebot | Succeeded to import "delete_image"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "upload_image"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "move_image"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "image_management"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "send_dinggong_voice"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "dialogue"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "group_welcome_msg"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "word_clouds"
08-20 18:39:55 [SUCCESS] nonebot | Succeeded to import "coser"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "aconfig"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "reset_today_query_user_data"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "bind"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "genshin_sign"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "query_memo"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "resin_remind"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "query_memo"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "query_role"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "query_user"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "query_resource_points"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "material_remind"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "almanac"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "genshin"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "open_cases"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "send_setu"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "update_setu"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "send_setu_"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "search_buff_skin_price"
08-20 18:39:56 [SUCCESS] nonebot | Succeeded to import "white2black_image"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "word_hanlde"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "message_handle"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "model"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "word_bank"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "fake_msg"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "search_image"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "roll"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "poetry"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "cover"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "jitang"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "comments_163"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "alapi"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix_pass_del_keyword"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix_add_keyword"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix_update"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix_show_info"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pix_gallery"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "russian"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "translate"
08-20 18:39:57 [SUCCESS] nonebot | Succeeded to import "pid_search"
08-20 18:39:58 [ERROR] nonebot | Failed to import "parse_bilibili_json"
Traceback (most recent call last):

  File "bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
    │       └ <function load_plugins at 0x7f81a6ae1550>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x7f81a6adb160>
           └ <nonebot.plugin.manager.PluginManager object at 0x7f81a4e80f70>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
                  │    │           │         │       │    └ <function PluginManager.list_plugins at 0x7f81a6adb040>
                  │    │           │         │       └ <nonebot.plugin.manager.PluginManager object at 0x7f81a4e80f70>
                  │    │           │         └ 'parse_bilibili_json'
                  │    │           └ 'parse_bilibili_json'
                  │    └ <function PluginManager.load_plugin at 0x7f81a6adb0d0>
                  └ <nonebot.plugin.manager.PluginManager object at 0x7f81a4e80f70>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 106, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x7f81a84079d0>
             └ <module 'importlib' from '/usr/lib/python3.8/importlib/__init__.py'>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.parse_bilibili_json'
           │          └ <function _gcd_import at 0x7f81a8527430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
                        └ <module 'plugins.parse_bilibili_json' from '/home/ZhenXunBOT/zhenxun_bot-main/plugins/parse_bilibili_json.py'>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/ZhenXunBOT/zhenxun_bot-main/plugins/parse_bilibili_json.py", line 17, in <module>
    from bilireq import video

ImportError: cannot import name 'video' from 'bilireq' (/root/.cache/pypoetry/virtualenvs/zhenxun-bot-raynKwDs-py3.8/lib/python3.8/site-packages/bilireq/__init__.py)
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "poke"
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "bilibili_sub"
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "my_info"
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "about"
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "wbtop"
08-20 18:39:58 [SUCCESS] nonebot | Succeeded to import "what_anime"
08-20 18:39:59 [SUCCESS] nonebot | Succeeded to import "draw_card"
08-20 18:39:59 [SUCCESS] nonebot | Succeeded to import "update_gocqhttp"
08-20 18:39:59 [SUCCESS] nonebot | Succeeded to import "web_ui"
08-20 18:39:59 [SUCCESS] nonebot | Succeeded to import "fudu"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "pixiv_rank_search"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "search_anime"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "weather"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "gold_redbag"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "quotations"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "black_word"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "music"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "statistics_hook"
08-20 18:40:00 [SUCCESS] nonebot | Succeeded to import "statistics_handle"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "statistics"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "update_picture"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "nbnhhsh"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "yiqing"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "luxun"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "one_friend"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "mute"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "bt"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "withdraw"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "sign_in"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "check"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "check_zhenxun_update"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "lifeRestart"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "other_hook"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "auth_hook"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "withdraw_message_hook"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "ban_hook"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "task_hook"
08-20 18:40:01 [SUCCESS] nonebot | Succeeded to import "chkdsk_hook"
08-20 18:40:01 [SUCCESS] nonebot | Running NoneBot...
08-20 18:40:01 [INFO] uvicorn | Started server process [32803]
08-20 18:40:01 [INFO] uvicorn | Waiting for application startup.
08-20 18:40:02 [INFO] services | Database loaded successfully!
08-20 18:40:02 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-20 18:40:02 [INFO] basic_plugins | 已成功加载 62 个非限制插件.
08-20 18:40:02 [INFO] utils | 已成功加载 5 个Cd限制.
08-20 18:40:02 [INFO] utils | 已成功加载 13 个Block限制.
08-20 18:40:02 [INFO] utils | 已成功加载 1 个Count限制.
08-20 18:40:10 [INFO] basic_plugins | 初始化数据完成...
08-20 18:40:10 [INFO] plugins | genshin_sign add_job：USER：1281843189 UID：214505646 2022-08-21 11:16:55.322603+08:00 原神自动签到
08-20 18:40:11 [INFO] plugins | 更新原神资源类型成功...
08-20 18:40:11 [WARNING] plugins | pretty_up_char 解析出错
08-20 18:40:11 [INFO] uvicorn | Application startup complete.



08-20 18:41:02 [SUCCESS] nonebot | ONEBOT V11  | [message.private.friend]: Message  from  "原神角色卡+uid"
08-20 18:41:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-20 18:41:02 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-20 18:41:02 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>

**Comment by unknownsno** [comment]
我怀疑你是来搞笑的！
首先，整个插件列表没有发现作者的插件名称，说明你根本没把插件放对地方，请自行查阅真寻文档，插件应该放在哪里，怎么放。
其次，私聊发送的"原神角色卡+uid"，意思是你要查询uid为“+uid”的玩家，你觉得米哈游有uid叫“+uid”的玩家吗？
最后，前面那么大个报错你不去解决，就去整别的插件，我这个强迫症实在是看不下去。。求你处理一下（虽然跟原神角色卡无关）。。解决方式在issues或者真寻的poetry.lock里面找bilireq模块版本，装这个版本

**Comment by JiJiang233** [comment]
> 我怀疑你是来搞笑的！ 首先，整个插件列表没有发现作者的插件名称，说明你根本没把插件放对地方，请自行查阅真寻文档，插件应该放在哪里，怎么放。 其次，私聊发送的"原神角色卡+uid"，意思是你要查询uid为“+uid”的玩家，你觉得米哈游有uid叫“+uid”的玩家吗？ 最后，前面那么大个报错你不去解决，就去整别的插件，我这个强迫症实在是看不下去。。求你处理一下（虽然跟原神角色卡无关）。。解决方式在issues或者真寻的poetry.lock里面找bilireq模块版本，装这个版本

哦天，我检查了一下文件夹发现之上传了一个文件夹（直接从7zip里面拖拽进去的），哦天啊，给你们添麻烦了

**Comment by CRAZYShimakaze** [comment]
看下单独放那个插件以后还有问题么，没问题就close啦。

**Comment by JiJiang233** [comment]
没有了
