### ISSUE TITLE
获取UID角色信息失败

### ISSUE THREAD

**Issue by HanakoLuna** [CRAZYShimakaze/zhenxun_extensive_plugin#2]
真寻版本0.1.5.9 
![1](https://user-images.githubusercontent.com/26741937/173027299-e82d9f86-d0a4-4ef9-9373-28f6f8f5bfbe.png)
显示网络超时，自检网络状态正常。
![2](https://user-images.githubusercontent.com/26741937/173027442-5527c3a5-2f73-4a92-b453-08ad8a4539f0.png)
希望获得解答，谢谢。

**Comment by CRAZYShimakaze** [comment]
应该不是每次都这样吧，导向的这个网站还处于测试阶段，网络状况时好时坏，会造成一定的加载问题，目前暂时没有想到什么好办法。

**Comment by HanakoLuna** [comment]
我测试了一下，发现Playwright貌似没有通过我的代理，我需要做什么修改才能让这个插件通过代理访问网站呢。

**Comment by CRAZYShimakaze** [comment]
问了一下大佬，貌似所有插件都会走真寻的全局代理的，你看看你的代理规则有没有问题。
