### ISSUE TITLE
genshin_role_card报错

### ISSUE THREAD

**Issue by A-Whisper** [CRAZYShimakaze/zhenxun_extensive_plugin#25]
系统：Debian11
Python版本：3.9

截图：
![C8FS_GUT %D~MI3KU4DG%A3](https://user-images.githubusercontent.com/60808770/186291618-d863707f-e21e-48f9-b34d-0d92223faacc.png)

已经找过issues了没看见有这个样子的（

**Comment by CRAZYShimakaze** [comment]
更新一下吧，已经修复了
