### ISSUE TITLE
无法触发的问题

### ISSUE THREAD

**Issue by IrisMiko** [CRAZYShimakaze/zhenxun_extensive_plugin#3]
![image](https://user-images.githubusercontent.com/60808770/173712596-ae2bf7db-3e08-429a-aba4-1545b7e7d21c.png)
![image](https://user-images.githubusercontent.com/60808770/173712621-07db96df-8a89-401c-99d1-7488354dacf2.png)
问题：后端无报错，命令无法触发。已尝试过使用代理
真寻版本：0.1.5.9
系统：Debian11

**Comment by CRAZYShimakaze** [comment]
从调用上来看是被发送本地图片的插件检测到了关键字，看看你的本地图库命名是不是和原神有关的

**Comment by IrisMiko** [comment]
确实和本地的图库冲突了，感谢！
![image](https://user-images.githubusercontent.com/60808770/173959939-0292aab3-e73f-45a0-b83f-e9484bf4ed50.png)

**Comment by whatxy** [comment]
> 确实和本地的图库冲突了，感谢！ ![图片](https://user-images.githubusercontent.com/60808770/173959939-0292aab3-e73f-45a0-b83f-e9484bf4ed50.png)

大佬怎么改的
