### ISSUE TITLE
genshin_role_card出现报错

### ISSUE THREAD

**Issue by q56535** [CRAZYShimakaze/zhenxun_extensive_plugin#34]
## 概述
bug概述（仅接受插件最新版本的问题，请确定自己使用的是最新版插件）
出现`name 'nonebot' is not defined`错误

## 系统环境
windows

## 重现步骤
命令信息(如果是原神插件请提供uid、角色名等)：
启动的时候直接报错

## Bug行为
无法加载插件

## 附件
附上图片或日志，日志请用格式：
 
![image](https://user-images.githubusercontent.com/26663837/187626537-b5aea93d-81aa-4d5b-ac32-31548978437e.png)

> ```
> 日志内容
> ```

**Comment by CRAZYShimakaze** [comment]
已修复。
