### ISSUE TITLE
原神角色面板'cannot unpact non-iterable int object'

### ISSUE THREAD

**Issue by McElaga** [CRAZYShimakaze/zhenxun_extensive_plugin#39]
## 概述
已更新最新版，使用一段时间出现的问题（是调用次数上限了吗）

## 系统环境
Ubuntu2004

## 重现步骤
任何相关指令

## Bug行为
真寻都不回复

## 附件
![Screenshot 2022-09-19 143551](https://user-images.githubusercontent.com/105900675/190962401-db9cb803-ac10-4d62-af87-443b462dc711.jpg)

**Comment by CRAZYShimakaze** [comment]
更新一下吧，已经修复啦。
