### ISSUE TITLE
我想加条反作弊代码，但是无论如何都无法跳出submit环节

### ISSUE THREAD

**Issue by uchihaZS** [CRAZYShimakaze/zhenxun_extensive_plugin#4]
![image](https://user-images.githubusercontent.com/38141497/174452377-11dacbad-5680-429f-8231-5ea148509589.png)
我想把在20秒内做出回答的人强行退出本次游戏，但是我那条语句只要超过20秒，还是会执行下面的答案判断行为，求大佬帮帮

**Comment by CRAZYShimakaze** [comment]
pull一下最新的代码再照着if语句改吧。
另外当前的逻辑是允许玩家只作答1道题就提交的，你这样检测可能会把这种情况误检。

**Comment by uchihaZS** [comment]
> pull一下最新的代码再照着if语句改吧。 另外当前的逻辑是允许玩家只作答1道题就提交的，你这样检测可能会把这种情况误检。

有没有办法可以把在20秒内作答的强行结束本轮游戏？

**Comment by CRAZYShimakaze** [comment]
> > pull一下最新的代码再照着if语句改吧。 另外当前的逻辑是允许玩家只作答1道题就提交的，你这样检测可能会把这种情况误检。
> 
> 
> 
> 有没有办法可以把在20秒内作答的强行结束本轮游戏？

你在最新版本的代码上按你之前的改就可以实现了,bot.finish记得改成send。
