### ISSUE TITLE
No module named 'plugins.genshin'

### ISSUE THREAD

**Issue by Aobaaaa** [CRAZYShimakaze/zhenxun_extensive_plugin#44]
## 概述
启动真寻报错No module named 'plugins.genshin'

## 系统环境
windows/Linux...

## 重现步骤
命令信息(如果是原神插件请提供uid、角色名等)：

## Bug行为
真寻如何反馈

## 附件
附上图片或日志，日志请用格式：
 
> ```
>11-03 10:25:18 [ERROR] nonebot | Failed to import "genshin_role_info"
>Traceback (most recent call last):
>  File "C:\bot\zhenxun_bot\bot.py", line 14, in <module>
>    nonebot.load_plugins("plugins")
>  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-DuaQwa0N-py3.9\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
>    return manager.load_all_plugins()
>  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-DuaQwa0N-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
>    return set(
>  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-DuaQwa0N-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
>    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-DuaQwa0N-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
>    module = importlib.import_module(
>  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-DuaQwa0N-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
>    super().exec_module(module)
>  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>  File "C:\bot\zhenxun_bot\plugins\genshin_role_info\__init__.py", line 17, in <module>
>    from plugins.genshin.query_user._models import Genshin
>ModuleNotFoundError: No module named 'plugins.genshin'
> ```

**Comment by CRAZYShimakaze** [comment]
看看是不是plugins目录下没有genshin文件了，这个应该是真寻本体自己的文件

**Comment by Aobaaaa** [comment]
> 看看是不是plugins目录下没有genshin文件了，这个应该是真寻本体自己的文件

好像是的，我煞笔了
