### ISSUE TITLE
【原神角色面板】部分角色圣遗物副词条属性不计算是这边移植的问题还是LittlePaimon那边的问题？

### ISSUE THREAD

**Issue by wlz-remake** [CRAZYShimakaze/zhenxun_extensive_plugin#47]
![B 2O4~Y_%Z68)VHMO5LBSCS](https://user-images.githubusercontent.com/105090141/200168544-e7301c2f-8e46-4c9b-8299-557c3a3ba5c7.PNG)
![5$NTH06P)G A}7QD)Q}0@~U](https://user-images.githubusercontent.com/105090141/200168550-526c1371-f3a4-48d6-a987-9b594af2eb6e.PNG)
尤拉的暴击率、肖宫的元素精通竟然不是有效词条么🤔

**Comment by CRAZYShimakaze** [comment]
优菈那个是bug了，已经修复了。
宵宫的是正常的，评分规则参照的是云崽的插件规则，具体的可以去看看云崽:[https://github.com/yoimiya-kokomi/miao-plugin](url)
