### ISSUE TITLE
笑死，21点无限做庄负债bug

### ISSUE THREAD

**Issue by ChrisYan6** [CRAZYShimakaze/zhenxun_extensive_plugin#48]
## 概述
笑死，身上有金币21点就可以无限做庄，输掉后导致负金币。

## 附件
> ```
> 日志内容
> ```
![21点bug](https://user-images.githubusercontent.com/42593868/204069180-e3f1808c-57ce-456f-b852-db765b747038.png)
![21点负债bug](https://user-images.githubusercontent.com/42593868/204069183-2762d984-27d4-4557-a5d8-8786320a5494.png)

**Comment by CRAZYShimakaze** [comment]
#49

**Comment by yaowan233** [comment]
其实这个是故意的，在原版中你负的越多然后第二天你签到你就得到的积分就会根据你负的积分给的越多的，相当于一个小彩蛋，群友都在想办法把积分搞到负数（
