### ISSUE TITLE
24插件不能使用

### ISSUE THREAD

**Issue by 15220526** [CRAZYShimakaze/zhenxun_extensive_plugin#6]
在输入24点之后出现了以下的报错，请问这是怎么回事呢
![image](https://user-images.githubusercontent.com/106159640/174541406-746ac0f0-234e-4d90-a2a4-bf36ec21f7a3.png)

**Comment by CRAZYShimakaze** [comment]
字体缺失的问题，pull一下最新代码吧，应该修复了
