### ISSUE TITLE
chatGPT插件没有上下文引用

### ISSUE THREAD

**Issue by PackageInstaller** [CRAZYShimakaze/zhenxun_extensive_plugin#65]
如题（不能变猫娘了，可恶）
![image](https://user-images.githubusercontent.com/80018096/222878569-af4f2192-6f11-4289-9e66-dbdbdf5ff3f2.png)

**Comment by lonelyenderman233** [comment]
> 如题（不能变猫娘了，可恶） ![image](https://user-images.githubusercontent.com/80018096/222878569-af4f2192-6f11-4289-9e66-dbdbdf5ff3f2.png)

你是不是没设置上下文长度

**Comment by PackageInstaller** [comment]
确实，我去试试

**Comment by PackageInstaller** [comment]
已解决，感谢
