### ISSUE TITLE
ChatGPT回复报错-问题反馈

### ISSUE THREAD

**Issue by mxk736850509** [CRAZYShimakaze/zhenxun_extensive_plugin#67]
## 概述

bot回复不准确
更换节点也一样的报错

## 系统环境

Windows10 22h2

## 重现步骤

世界树 你在吗

## Bug行为

“世界树 你在吗”，回复报错

## 附件
附上图片或日志，日志请用格式：
 
![聊天弹出](https://user-images.githubusercontent.com/39251155/223009877-3bd708b6-18b6-4682-8606-da72d95493f7.png)

![真寻](https://user-images.githubusercontent.com/39251155/223009887-341baca2-7429-42ab-9dc5-0d883f8ce654.png)

> ```
> 日志内容
> ```

**Comment by CRAZYShimakaze** [comment]
应该是网络问题，我这边是正常的。

**Comment by mxk736850509** [comment]
好吧 看来是魔法问题，浏览器连OpenAI都是正常的
