### ISSUE TITLE
原神角色卡不知道为啥老是捕捉不到指令

### ISSUE THREAD

**Issue by kuai364354200** [CRAZYShimakaze/zhenxun_extensive_plugin#77]
## 概述
之前懒了，适配迪希雅的版本没更，从艾尔海森版直接跳到米卡版，然后就用不了了
艾尔海森那版好像还能正常用的

## 系统环境
Ubuntu 20.04 LTS
真寻 v0.1.6.7

## 日志内容
![图片](https://user-images.githubusercontent.com/72508741/229286875-c015ceca-8ece-4e85-8c2f-8d4241f9f71a.png)
![图片](https://user-images.githubusercontent.com/72508741/229286861-9b1eff7e-de89-412a-98c5-00acc50d9035.png)

**Comment by kuai364354200** [comment]
![图片](https://user-images.githubusercontent.com/72508741/229287107-96995286-33e0-4d6c-8078-c6ec58191ce0.png)

04-01 19:44:07 [SUCCESS] nonebot | OneBot V11 1504429250 | [message.private.friend]: Message 946957492 from 364354200 "原神角色卡 195939617 甘雨"
04-01 19:44:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-01 19:44:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-01 19:44:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main)
04-01 19:44:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-01 19:44:07 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-01 19:44:07 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
04-01 19:44:07 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-01 19:44:07 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-01 19:44:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
04-01 19:44:10 [INFO] services | USER 364354200 GROUP  问题：原神角色卡 195939617 甘雨 ---- 回答：这日子啊，好无聊哦...
04-01 19:44:10 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete
04-01 19:44:18 [SUCCESS] nonebot | OneBot V11 1504429250 | [message.private.friend]: Message 1333156898 from 364354200 "原神角色卡\d195939617\d甘雨"
04-01 19:44:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-01 19:44:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-01 19:44:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main)
04-01 19:44:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-01 19:44:18 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-01 19:44:18 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
04-01 19:44:18 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-01 19:44:18 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-01 19:44:18 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
04-01 19:44:22 [INFO] services | USER 364354200 GROUP  问题：原神角色卡\d195939617\d甘雨 ---- 回答：这日子啊，好无聊哦...
04-01 19:44:22 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete
04-01 19:44:36 [SUCCESS] nonebot | OneBot V11 1504429250 | [message.private.friend]: Message -540458573 from 364354200 "原神角色卡 195939617 甘雨"
04-01 19:44:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-01 19:44:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-01 19:44:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main)
04-01 19:44:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-01 19:44:36 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-01 19:44:36 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
04-01 19:44:36 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-01 19:44:36 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-01 19:44:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
04-01 19:44:40 [INFO] services | USER 364354200 GROUP  问题：原神角色卡 195939617 甘雨 ---- 回答：[CQ:face,id=81]太深奥了吧,我真心没弄明白您的话
04-01 19:44:40 [INFO] nonebot | Matcher(type='message', module=plugins.ai) running complete

**Comment by CRAZYShimakaze** [comment]
看日志插件都没有调用，应该是启动的时候就报错了。看看启动日志

**Comment by kuai364354200** [comment]
> 看日志插件都没有调用，应该是启动的时候就报错了。看看启动日志

欸原来是空格的问题，不加空格就好了
![图片](https://user-images.githubusercontent.com/72508741/229530841-fc70efb5-96e0-4859-8a38-72130081912d.png)
04-03 21:53:01 [SUCCESS] nonebot | OneBot V11 1504429250 | [message.private.friend]: Message 1818817188 from 364354200 "原神角色卡195939617 甘雨"
04-03 21:53:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-03 21:53:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-03 21:53:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main)
04-03 21:53:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-03 21:53:01 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-03 21:53:01 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
04-03 21:53:01 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-03 21:53:01 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-03 21:53:01 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.genshin_role_info)
04-03 21:53:05 [INFO] services | 下载 https://enka.network/ui/UI_Gacha_AvatarImg_Ganyu.png 成功.. Path：/home/zhenxun-bot/data/genshin_role_info/res/character/甘雨.png
04-03 21:53:06 [INFO] services | 下载 https://enka.network/ui/Skill_A_02.png 成功.. Path：/home/zhenxun-bot/data/genshin_role_info/res/skill/Skill_A_02.png
04-03 21:53:06 [INFO] services | 下载 https://enka.network/ui/Skill_S_Ganyu_01.png 成功.. Path：/home/zhenxun-bot/data/genshin_role_info/res/skill/Skill_S_Ganyu_01.png
04-03 21:53:08 [INFO] services | 下载 https://enka.network/ui/Skill_E_Ganyu_01.png 成功.. Path：/home/zhenxun-bot/data/genshin_role_info/res/skill/Skill_E_Ganyu_01.png
04-03 21:53:09 [INFO] services | 下载 https://enka.network/ui/UI_EquipIcon_Bow_Zephyrus.png 成功.. Path：/home/zhenxun-bot/data/genshin_role_info/res/weapon/UI_EquipIcon_Bow_Zephyrus.png
04-03 21:53:16 [SUCCESS] nonebot | OneBot V11 1504429250 | [message.private.friend]: Message 212826945 from 364354200 "原神角色卡 195939617 甘雨"
04-03 21:53:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-03 21:53:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-03 21:53:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main)
04-03 21:53:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-03 21:53:16 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-03 21:53:16 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_intercept_withdraw-main) running complete
04-03 21:53:16 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-03 21:53:16 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-03 21:53:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.ai)
04-03 21:53:20 [INFO] services | USER 364354200 GROUP  问题：原神角色卡 195939617 甘雨 ---- 回答：表酱紫讲话好不，伦家听不习惯

**Comment by CRAZYShimakaze** [comment]
最新版加不加空格都可以识别了
