### ISSUE TITLE
chatgpt插件无法正常使用

### ISSUE THREAD

**Issue by HouraisanHoshi** [CRAZYShimakaze/zhenxun_extensive_plugin#78]
## 概述
输入 世界树+语句都是回复 All connection attempts failed 

## 系统环境
Linux

## 重现步骤
输入 世界树+语句

## Bug行为
回复 All connection attempts failed

## 附件
![506eeeb2e4b129d9](https://user-images.githubusercontent.com/59908591/229298235-4347ca43-e027-4226-8edc-57eccf2ad054.jpg)

![IMG_20230401_232408](https://user-images.githubusercontent.com/59908591/229298214-568b968a-112a-4058-933b-3976169a508c.jpg)

**Comment by CRAZYShimakaze** [comment]
应该是网络问题，尝试下挂代理
