### ISSUE TITLE
带分数的计算有bug

### ISSUE THREAD

**Issue by zyj3421** [CRAZYShimakaze/zhenxun_extensive_plugin#8]
bug：6741的一个解法4/(7/6-1)无法通过验证
![QQ截图20220629203330](https://user-images.githubusercontent.com/6783147/176437294-6b4a1b73-3c35-4148-ab72-0488b3c70276.png)

**Comment by CRAZYShimakaze** [comment]
目前结算的逻辑是不支持含分数解的，给出的四个数必定有不含分数运算的解，如果想要支持分数解，修改以下判断代码：
`if eval(submit) == 24:`
改为
`if abs(eval(submit)-24) < 0.01:`
