### ISSUE TITLE
更新最新版本插件后报错

### ISSUE THREAD

**Issue by ZZZ-zero** [CRAZYShimakaze/zhenxun_extensive_plugin#88]
![image](https://user-images.githubusercontent.com/30883525/236612881-dd75f1c1-3629-4830-9f14-758a7d740cdf.png)
如图，更新白术版本后无法运行

**Comment by MobiusT** [comment]
genshin_role_info插件自2.4版本起要求真寻升级至v0.1.6.7版本（数据库舍弃gino使用tortoise）
