### ISSUE TITLE
无法加载插件genshin_role_card

### ISSUE THREAD

**Issue by HA-JD** [CRAZYShimakaze/zhenxun_extensive_plugin#9]
已安装ascii isdigit 报错ModuleNotFoundError: No module named '_curses'

**Comment by CRAZYShimakaze** [comment]
这个插件应该是不需要额外装依赖的，你看看是不是本身的环境没装好

**Comment by CRAZYShimakaze** [comment]
Windows环境下缺少curses依赖造成，可以尝试通过`pip install windows-curses`修复。
