### ISSUE TITLE
原神角色面板报错

### ISSUE THREAD

**Issue by CBTtreasure** [CRAZYShimakaze/zhenxun_extensive_plugin#90]
## 概述
角色面板突然报错 任何指令都无反应 插件及真寻本体都是最新版，之前还好好的 昨晚服务器死机后就出现了这个问题
如图
![image](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/134543146/98e8cd7c-5ec7-453f-ae1a-58c3bc523aa5)

**Comment by CBTtreasure** [comment]
啊 已经修好了 将 __init__.py 的109和111行中的 user_qq 均改成 user_id 就好了
望修复

**Comment by CRAZYShimakaze** [comment]
你用的是真寻的最新commit版么？现在插件适配没有那么及时的，一般都按最新的release来适配。
