### ISSUE TITLE
星原插件使用感受

### ISSUE THREAD

**Issue by SuLiuming** [CRAZYShimakaze/zhenxun_extensive_plugin#91]
不过都是小问题，个人也能修改，只建议不强求。

 星铁角色面板部分 ：
  1 缺少绑定解绑的帮助；
  2 绑定方式能否跟原神绑定方式一致呢（目前原神：原神绑定uidxxxxx  ；目前星铁：绑定星铁uidxxxxxx  一个绑定在前，一个绑定在 
     后，使用时候容易混淆）

 原神角色面板部分 ：
 1  我/他的角色--》我/他的原神角色 （目前星铁是  我的星铁角色）
 2 更新/刷新面板 (uid)--》更新/刷新原神面板 (uid) （目前星铁是  更新/刷新星铁面板 (uid)）

  

 星铁原神攻略部分：
    1原神和星铁的部分指令容易混淆（目前原神：角色配装/角色评级/武器推荐     目前星铁   角色配队/光锥评级   都有角色，光锥从某 
      种意义上也可以说是武器，使用也容易混淆..）

 最后要是能有个记录蛋池出货的插件就更好了（贪得无厌）

**Comment by CRAZYShimakaze** [comment]
原神插件近期会更新一版，你说的有一些已经改好了

**Comment by SuLiuming** [comment]
> 

体验了下新版 怎么说呢 需要重新绑定还是略麻烦的 要是能兼容之前绑定就好了

**Comment by SuLiuming** [comment]
大概在130行 我是这样改的 ：
async def get_msg_uid(event):
    at_user = get_message_at(event.json())
    user_qq = at_user[0] if at_user else event.user_id
    genshin_user = await Genshin.get_or_none(user_qq=user_qq)
    if genshin_user and check_uid(genshin_user.uid):
        return genshin_user.uid
    else:
        uid = get_uid(user_qq)
        if not uid:
            await artifact_list.finish("请绑定uid后再查询！")
        if not check_uid(uid):
            await artifact_list.finish(f"绑定的uid{uid}不合法，请重新绑定!")
        return uid

**Comment by SuLiuming** [comment]
不过解绑时候会提示两次 暂时是吧        await unbind.send("用户数据删除成功...") 这句删了 。。。

**Comment by CRAZYShimakaze** [comment]
又更新了一版，支持自动导入数据库里的绑定uid了，不过要先把上一版生成的qq2uid.json删掉
