### ISSUE TITLE
name "check_gold" is not defined

### ISSUE THREAD

**Issue by huihuiismywife** [CRAZYShimakaze/zhenxun_extensive_plugin#93]
原神角色面板的“群圣遗物榜单”和“圣遗物榜单”以及“角色圣遗物推荐”这个三个功能在使用时发生如下报错
![Y7N628_WB4TYDS(OZ{U(TNF](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/assets/107234845/61ed256d-e62d-4af5-8da8-3c180afbc128)

**Comment by CRAZYShimakaze** [comment]
更新一下吧，，，不小心把我自己写的扣金币函数提交上去了(／。＼)
